from typing import Protocol
from uuid import UUID

from app.domain.entities import Request
from app.domain.enums import RequestStatus


class RequestRepository(Protocol):
    def save(self, request: Request) -> Request: ...
    def get_by_id(self, request_id: UUID) -> Request | None: ...
    def update_status(self, request_id: UUID, status: RequestStatus) -> None: ...


class EventPublisher(Protocol):
    def publish(self, topic: str, key: str, payload: dict) -> None: ...


class CachePort(Protocol):
    def get(self, key: str) -> str | None: ...
    def set(self, key: str, value: str, ttl: int) -> None: ...
    def delete(self, key: str) -> None: ...
